### PR TITLE
Update 1.8.9

### PR DESCRIPTION
**Pull request by Illyohs**
The update is pretty straight forward no bugs by what I can see mostly mapping updates.

### CODE REVIEW

**Comment by sdj64** [comment]
Hi, thanks for this.  Did you encounter a bug with leaves not disappearing, and if you did, did you try to fix it?

**Comment by Illyohs** [comment]
Not with what I saw but I can make another pass through and try to find it.

**Comment by Illyohs** [comment]
Was it your leaves of vanilla leaves?

**Comment by Illyohs** [comment]
looks like leaves decay just really slowly

**Comment by sdj64** [comment]
I thought that it had something to do with my leaves not correctly recognizing when they should start decaying.

**Pull request merged**
